# Generated by Django 6.0 on 2026-01-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_resume_file_resume_candidate_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
